### PR TITLE
AKS diagnostic bug resolved & storage diagnostic added

### LINKED ISSUE #872: AKS Diagnostics - Availability diagnostic error
**Bug Description**
Clicking the "Known Issues, Availability and Performance Diagnostics" button under any cluster results in the following error: 

```
Error invoking aks-category-availability-perf detector: RestError: detector aks-category-availability-perf not found
```

**Platform**
vscode, ubuntu

**To Reproduce**
1. Right click on any AKS cluster
2. Select Run AKS Diagnostics -> Known Issues, Availability and Performance Diagnostics

**Expected behavior**
It should bring up a panel with data from the diagnostics report.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by tejhan**
## Description

This PR resolves #872 

- Fixed bug when running `AKS Diagnostics > Known Issues, Availability and Performance`
- Added storage diagnostics
- Updated periscope information link

## Screenshots

AKS Diagnostics - Frame 3 (2)

## Related Issues

- Closes #872

### CODE REVIEW

**Comment by tejhan** [comment]
@microsoft-github-policy-service agree

File: src/commands/utils/detectors.ts [hunk 1]
```diff
@@ -98,7 +98,7 @@ export async function getDetectorInfo(
             clusterNode.name,
             "detectors",
             detectorName,
-            "2019-08-01",
+            "2024-05-01",
```
Comment (Tatsinnit) [inline src/commands/utils/detectors.ts:101]: 👍 nice, do you have handy link for archiving of all past versions of this API version, if so please share here.

File: package.json [hunk 2]
```diff
@@ -221,8 +221,12 @@
                 "title": "Node Health"
             },
             {
-                "command": "aks.aksKnownIssuesAvailabilityPerformanceDiagnostics",
-                "title": "Known Issues, Availability and Performance"
+                "command": "aks.aksCCPAvailabilityPerformanceDiagnostics",
+                "title": "Cluster and Control Plane Availability and Performance"
+            },
+            {
+                "command": "aks.aksStorageDiagnostics",
```
Comment (Tatsinnit) [inline package.json:228]: Is this new command? or improvement of any existing one? Thanks.

I did read your docs, the only thing I wanted to check is that this is extra you think is good one to add as improvements or someone asked to do so? This looks harmless. (Worth to archive thought process)

**Review by Tatsinnit — COMMENTED** [review]
Thanks for this PR, looks great here are some minor comments to go through, thank you so much <3

File: webview-ui/src/Periscope/Periscope.tsx [hunk 3]
```diff
@@ -30,7 +30,7 @@ export function Periscope(initialState: InitialState) {
                 AKS Periscope collects and exports node and pod logs into an Azure Blob storage account to help you
                 analyse and identify potential problems or easily share the information during the troubleshooting
                 process.
-                <VSCodeLink href="https://aka.ms/vscode-aks-periscope">&nbsp;Learn more</VSCodeLink>
+                <VSCodeLink href="https://github.com/Azure/aks-periscope">&nbsp;Learn more</VSCodeLink>
```
[the remark this answers is not in the document]
Comment (tejhan) [reply webview-ui/src/Periscope/Periscope.tsx]: Done 👍

File: package.json (hunk 2 above)
Comment (tejhan) [reply package.json:228]: Yep, it's a new command that queries 5 new detectors related to Storage diagnostics. Added it as an improvement since it's a more recent diagnostic feature that's available on the portal but not currently in the extension. 👍
AKS Diagnostics - Frame 4

Comment (ReinierCC) [reply package.json:228]: Was the old command deprecated, and the new command includes the previous features and more?

Comment (tejhan) [reply package.json:228]: My above comment was referring to the new aksStorageDiagnostics command, I assumed that's the one Tats was referring to in the code snippet. In regards to the aksCCPAvailabilityPerformanceDiagnostics command, that's just a rename of the former aksKnownIssuesAvailabilityPerformanceDiagnostics command, which was using an outdated API endpoint. This was just a change in verbiage to reflect what's currently seen in the Azure portal & ARM API. 👍

**Review by Tatsinnit — APPROVED** [review]

**Review by hsubramanianaks — APPROVED** [review]

**Comment by tejhan** [comment]
VSIX file for testing - > [vscode-aks-tools-1.4.8diagnostic-fix.zip](https://github.com/user-attachments/files/16852408/vscode-aks-tools-1.4.8diagnostic-fix.zip)

File: package.json (hunk 2 above)
Comment (ReinierCC) [reply package.json:228]: ahh ok, thanks for the clarification
